// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicEditableBizItem,
  DefaultEditableBizItemProps,
} from "./plasmic/easytime/PlasmicEditableBizItem";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
interface EditableBizItemProps extends DefaultEditableBizItemProps {
  value: string;
  onChange: (value: string) => void;
  onDeleteClick: () => void;
}

function EditableBizItem({
  value,
  onChange,
  onDeleteClick,
}: EditableBizItemProps) {
  return (
    <PlasmicEditableBizItem
      input={{
        value,
        onChange: (e) => {
          onChange(e.target.value);
        },
      }}
      del={{ onClick: onDeleteClick }}
    />
  );
}

export default EditableBizItem;
