// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicLogRecord,
  DefaultLogRecordProps,
} from "./plasmic/easytime/PlasmicLogRecord";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { useRouter } from "next/router";
interface LogRecordProps extends DefaultLogRecordProps {
  recId?: string;
}

function LogRecord_(props: LogRecordProps, ref: HTMLElementRefOf<"div">) {
  const router = useRouter();
  return (
    <PlasmicLogRecord
      root={{ ref }}
      {...props}
      edit={{
        onClick() {
          if (!props.recId) {
            return;
          }
          router.push(`/log/${props.recId}`);
        },
      }}
    />
  );
}

const LogRecord = React.forwardRef(LogRecord_);
export default LogRecord;
