// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicLogRecordHeaderItem,
  DefaultLogRecordHeaderItemProps,
} from "./plasmic/easytime/PlasmicLogRecordHeaderItem";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export type Topics = "biz" | "start" | "end" | "report" | "duration";
export type Order = "asc" | "desc";
interface LogRecordHeaderItemProps extends DefaultLogRecordHeaderItemProps {
  topic: Topics;
  label: string;
  value: [Topics, Order];
  onChange: (topic: [Topics, Order]) => void;
}

function LogRecordHeaderItem_(
  { topic, label, value, onChange }: LogRecordHeaderItemProps,
  ref: HTMLElementRefOf<"div">
) {
  const handleClick = () => {
    onChange([topic, value[1] === "asc" ? "desc" : "asc"]);
  };
  return (
    <PlasmicLogRecordHeaderItem
      root={{ ref }}
      onClick={handleClick}
      order={topic == value[0] ? value[1] : undefined}
      label={label}
    />
  );
}

const LogRecordHeaderItem = React.forwardRef(LogRecordHeaderItem_);
export default LogRecordHeaderItem;
