// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useRef } from "react";
import {
  PlasmicTimeInput,
  DefaultTimeInputProps,
} from "./plasmic/easytime/PlasmicTimeInput";

interface TimeInputProps extends DefaultTimeInputProps {
  value: [string, string];
  onChange: (value: [string, string]) => void;
}

function TimeInput({ value, onChange }: TimeInputProps) {
  const ref = useRef<HTMLInputElement>(null);
  if (!value) {
    value = ["", ""];
  }
  return (
    <PlasmicTimeInput
      hour={{
        value: value[0],
        onChange: (e) => {
          const val = e.target.value;
          if (val.length == 2) {
            ref.current?.focus();
          }
          onChange([val, value[1]]);
        },
      }}
      minute={{
        value: value[1],
        onChange: (e) => onChange([value[0], e.target.value]),
        ref: ref,
      }}
    />
  );
}
export default TimeInput;
