// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicYmdhmInput } from "./plasmic/easytime/PlasmicYmdhmInput";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { dateToMinstamp, minstampToDate } from "../utils/date";

type Props = {
  /** minutestamp */
  value: number;
  /** onChange */
  onChange: (value: number) => void;
};
function YmdhmInput({ value, onChange }: Props) {
  const date = minstampToDate(value);
  return (
    <PlasmicYmdhmInput
      year={{
        value: date.getFullYear(),
        onChange: (e) => {
          const year = parseInt(e.target.value.slice(-4), 10);
          date.setFullYear(year);
          onChange(dateToMinstamp(date));
        },
      }}
      month={{
        value: date.getMonth() + 1,
        onChange: (e) => {
          const month = parseInt(e.target.value.slice(-2), 10);
          date.setMonth(month - 1);
          onChange(dateToMinstamp(date));
        },
      }}
      day={{
        value: date.getDate(),
        onChange: (e) => {
          const day = parseInt(e.target.value.slice(-2), 10);
          date.setDate(day);
          onChange(dateToMinstamp(date));
        },
      }}
      hour={{
        value: date.getHours(),
        onChange: (e) => {
          const hour = parseInt(e.target.value.slice(-2), 10);
          date.setHours(hour);
          onChange(dateToMinstamp(date));
        },
      }}
      minute={{
        value: date.getMinutes(),
        onChange: (e) => {
          const minute = parseInt(e.target.value.slice(-2), 10);
          date.setMinutes(minute);
          onChange(dateToMinstamp(date));
        },
      }}
    />
  );
}

export default YmdhmInput;
