// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mBKHaRhjQbiZuznDyARcTS
// Component: 8PUOayqXwP
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_easytime.module.css"; // plasmic-import: mBKHaRhjQbiZuznDyARcTS/projectcss
import * as sty from "./PlasmicHeaderButton.module.css"; // plasmic-import: 8PUOayqXwP/css

export type PlasmicHeaderButton__VariantMembers = {};

export type PlasmicHeaderButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeaderButton__VariantsArgs;
export const PlasmicHeaderButton__VariantProps = new Array<VariantPropType>();

export type PlasmicHeaderButton__ArgsType = {
  children?: React.ReactNode;
  to?: string | PageHref;
};

type ArgPropType = keyof PlasmicHeaderButton__ArgsType;
export const PlasmicHeaderButton__ArgProps = new Array<ArgPropType>(
  "children",
  "to"
);

export type PlasmicHeaderButton__OverridesType = {
  root?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultHeaderButtonProps {
  children?: React.ReactNode;
  to?: string | PageHref;
  className?: string;
}

function PlasmicHeaderButton__RenderFunc(props: {
  variants: PlasmicHeaderButton__VariantsArgs;
  args: PlasmicHeaderButton__ArgsType;
  overrides: PlasmicHeaderButton__OverridesType;
  dataFetches?: PlasmicHeaderButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.PlasmicLink
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      component={Link}
      href={args.to}
      platform={"nextjs"}
    >
      {p.renderPlasmicSlot({
        defaultContents: "Label",
        value: args.children,
        className: classNames(sty.slotChildren),
      })}
    </p.PlasmicLink>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeaderButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeaderButton__VariantsArgs;
    args?: PlasmicHeaderButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHeaderButton__Fetches;
  } & Omit<PlasmicHeaderButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHeaderButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHeaderButton__ArgProps,
      internalVariantPropNames: PlasmicHeaderButton__VariantProps,
    });

    const { dataFetches } = props;

    return PlasmicHeaderButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeaderButton";
  } else {
    func.displayName = `PlasmicHeaderButton.${nodeName}`;
  }
  return func;
}

export const PlasmicHeaderButton = Object.assign(
  // Top-level PlasmicHeaderButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHeaderButton
    internalVariantProps: PlasmicHeaderButton__VariantProps,
    internalArgProps: PlasmicHeaderButton__ArgProps,
  }
);

export default PlasmicHeaderButton;
/* prettier-ignore-end */
