// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mBKHaRhjQbiZuznDyARcTS
// Component: FN-EzPooHT
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import Checkbox from "../../Checkbox"; // plasmic-import: j-zkNvYO40/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_easytime.module.css"; // plasmic-import: mBKHaRhjQbiZuznDyARcTS/projectcss
import sty from "./PlasmicTimeInput.module.css"; // plasmic-import: FN-EzPooHT/css

export type PlasmicTimeInput__VariantMembers = {
  dayAgo: "dayAgo";
};
export type PlasmicTimeInput__VariantsArgs = {
  dayAgo?: SingleBooleanChoiceArg<"dayAgo">;
};
type VariantPropType = keyof PlasmicTimeInput__VariantsArgs;
export const PlasmicTimeInput__VariantProps = new Array<VariantPropType>(
  "dayAgo"
);

export type PlasmicTimeInput__ArgsType = {};
type ArgPropType = keyof PlasmicTimeInput__ArgsType;
export const PlasmicTimeInput__ArgProps = new Array<ArgPropType>();

export type PlasmicTimeInput__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  hour?: p.Flex<"input">;
  minute?: p.Flex<"input">;
  dayAgoCheckbox?: p.Flex<"div">;
  checkbox?: p.Flex<typeof Checkbox>;
};

export interface DefaultTimeInputProps {
  dayAgo?: SingleBooleanChoiceArg<"dayAgo">;
  className?: string;
}

function PlasmicTimeInput__RenderFunc(props: {
  variants: PlasmicTimeInput__VariantsArgs;
  args: PlasmicTimeInput__ArgsType;
  overrides: PlasmicTimeInput__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants,
  };

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <input
          data-plasmic-name={"hour"}
          data-plasmic-override={overrides.hour}
          className={classNames(projectcss.all, projectcss.input, sty.hour)}
          size={1 as const}
          type={"text" as const}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___1ZcV
          )}
        >
          {":"}
        </div>

        <input
          data-plasmic-name={"minute"}
          data-plasmic-override={overrides.minute}
          className={classNames(projectcss.all, projectcss.input, sty.minute)}
          size={1 as const}
          type={"text" as const}
        />
      </div>

      <p.Stack
        as={"div"}
        data-plasmic-name={"dayAgoCheckbox"}
        data-plasmic-override={overrides.dayAgoCheckbox}
        hasGap={true}
        className={classNames(projectcss.all, sty.dayAgoCheckbox, {
          [sty.dayAgoCheckboxdayAgo]: hasVariant(variants, "dayAgo", "dayAgo"),
        })}
      >
        <Checkbox
          data-plasmic-name={"checkbox"}
          data-plasmic-override={overrides.checkbox}
          className={classNames("__wab_instance", sty.checkbox, {
            [sty.checkboxdayAgo]: hasVariant(variants, "dayAgo", "dayAgo"),
          })}
          selected={hasVariant(variants, "dayAgo", "dayAgo") ? true : undefined}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__x3F9S
          )}
        >
          {"前日"}
        </div>
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "hour", "minute", "dayAgoCheckbox", "checkbox"],
  freeBox: ["freeBox", "hour", "minute"],
  hour: ["hour"],
  minute: ["minute"],
  dayAgoCheckbox: ["dayAgoCheckbox", "checkbox"],
  checkbox: ["checkbox"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  hour: "input";
  minute: "input";
  dayAgoCheckbox: "div";
  checkbox: typeof Checkbox;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTimeInput__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTimeInput__VariantsArgs;
    args?: PlasmicTimeInput__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTimeInput__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTimeInput__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTimeInput__ArgProps,
          internalVariantPropNames: PlasmicTimeInput__VariantProps,
        }),
      [props, nodeName]
    );

    return PlasmicTimeInput__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTimeInput";
  } else {
    func.displayName = `PlasmicTimeInput.${nodeName}`;
  }
  return func;
}

export const PlasmicTimeInput = Object.assign(
  // Top-level PlasmicTimeInput renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    hour: makeNodeComponent("hour"),
    minute: makeNodeComponent("minute"),
    dayAgoCheckbox: makeNodeComponent("dayAgoCheckbox"),
    checkbox: makeNodeComponent("checkbox"),

    // Metadata about props expected for PlasmicTimeInput
    internalVariantProps: PlasmicTimeInput__VariantProps,
    internalArgProps: PlasmicTimeInput__ArgProps,
  }
);

export default PlasmicTimeInput;
/* prettier-ignore-end */
