// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j56rC5AhmHAm1fzGMT7yJp
// Component: RA2ky5lkOo
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TableRow from "../../TableRow"; // plasmic-import: _Jz9ilBFcY/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_react_invoice.module.css"; // plasmic-import: j56rC5AhmHAm1fzGMT7yJp/projectcss
import * as sty from "./PlasmicTableRowHeader.module.css"; // plasmic-import: RA2ky5lkOo/css

export type PlasmicTableRowHeader__VariantMembers = {};

export type PlasmicTableRowHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicTableRowHeader__VariantsArgs;
export const PlasmicTableRowHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicTableRowHeader__ArgsType = {};
type ArgPropType = keyof PlasmicTableRowHeader__ArgsType;
export const PlasmicTableRowHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicTableRowHeader__OverridesType = {
  root?: p.Flex<"div">;
  tableRow?: p.Flex<typeof TableRow>;
};

export interface DefaultTableRowHeaderProps {
  className?: string;
}

function PlasmicTableRowHeader__RenderFunc(props: {
  variants: PlasmicTableRowHeader__VariantsArgs;
  args: PlasmicTableRowHeader__ArgsType;
  overrides: PlasmicTableRowHeader__OverridesType;
  dataFetches?: PlasmicTableRowHeader__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <TableRow
        data-plasmic-name={"tableRow"}
        data-plasmic-override={overrides.tableRow}
        amount={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.freeBox__q8AAx
            )}
          >
            {"数量"}
          </div>
        }
        className={classNames("__wab_instance", sty.tableRow)}
        price={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.freeBox__mmPNt
            )}
          >
            {"単価"}
          </div>
        }
        topic={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.freeBox__tthFp
            )}
          >
            {"摘要"}
          </div>
        }
        total={
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.freeBox__c0Dcw
            )}
          >
            {"合計"}
          </div>
        }
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "tableRow"],
  tableRow: ["tableRow"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  tableRow: typeof TableRow;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTableRowHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTableRowHeader__VariantsArgs;
    args?: PlasmicTableRowHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTableRowHeader__Fetches;
  } & Omit<PlasmicTableRowHeader__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTableRowHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTableRowHeader__ArgProps,
      internalVariantPropNames: PlasmicTableRowHeader__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTableRowHeader__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTableRowHeader";
  } else {
    func.displayName = `PlasmicTableRowHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicTableRowHeader = Object.assign(
  // Top-level PlasmicTableRowHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tableRow: makeNodeComponent("tableRow"),

    // Metadata about props expected for PlasmicTableRowHeader
    internalVariantProps: PlasmicTableRowHeader__VariantProps,
    internalArgProps: PlasmicTableRowHeader__ArgProps
  }
);

export default PlasmicTableRowHeader;
/* prettier-ignore-end */
