// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j56rC5AhmHAm1fzGMT7yJp
// Component: yop_kEKULA
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_react_invoice.module.css"; // plasmic-import: j56rC5AhmHAm1fzGMT7yJp/projectcss
import * as sty from "./PlasmicPayTo.module.css"; // plasmic-import: yop_kEKULA/css

export type PlasmicPayTo__VariantMembers = {};

export type PlasmicPayTo__VariantsArgs = {};
type VariantPropType = keyof PlasmicPayTo__VariantsArgs;
export const PlasmicPayTo__VariantProps = new Array<VariantPropType>();

export type PlasmicPayTo__ArgsType = {
  children?: React.ReactNode;
  due?: React.ReactNode;
};

type ArgPropType = keyof PlasmicPayTo__ArgsType;
export const PlasmicPayTo__ArgProps = new Array<ArgPropType>("children", "due");

export type PlasmicPayTo__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultPayToProps {
  children?: React.ReactNode;
  due?: React.ReactNode;
  className?: string;
}

function PlasmicPayTo__RenderFunc(props: {
  variants: PlasmicPayTo__VariantsArgs;
  args: PlasmicPayTo__ArgsType;
  overrides: PlasmicPayTo__OverridesType;
  dataFetches?: PlasmicPayTo__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.freeBox___3HwGf
        )}
      >
        {"下記にお振込みください"}
      </div>

      <div className={classNames(defaultcss.all, sty.freeBox__tsbTl)}>
        {p.renderPlasmicSlot({
          defaultContents: "チンコ銀行 おっぱい支店 普通 1919810",
          value: args.children
        })}
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox__vi6Oi)}
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__ww1Vw
          )}
        >
          {"支払い期限: "}
        </div>

        {p.renderPlasmicSlot({
          defaultContents: "2021/09/05",
          value: args.due
        })}
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPayTo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPayTo__VariantsArgs;
    args?: PlasmicPayTo__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicPayTo__Fetches;
  } & Omit<PlasmicPayTo__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPayTo__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPayTo__ArgProps,
      internalVariantPropNames: PlasmicPayTo__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicPayTo__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPayTo";
  } else {
    func.displayName = `PlasmicPayTo.${nodeName}`;
  }
  return func;
}

export const PlasmicPayTo = Object.assign(
  // Top-level PlasmicPayTo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicPayTo
    internalVariantProps: PlasmicPayTo__VariantProps,
    internalArgProps: PlasmicPayTo__ArgProps
  }
);

export default PlasmicPayTo;
/* prettier-ignore-end */
