// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j56rC5AhmHAm1fzGMT7yJp
// Component: _Jz9ilBFcY
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_react_invoice.module.css"; // plasmic-import: j56rC5AhmHAm1fzGMT7yJp/projectcss
import * as sty from "./PlasmicTableRow.module.css"; // plasmic-import: _Jz9ilBFcY/css

export type PlasmicTableRow__VariantMembers = {
  header: "header";
};

export type PlasmicTableRow__VariantsArgs = {
  header?: SingleBooleanChoiceArg<"header">;
};

type VariantPropType = keyof PlasmicTableRow__VariantsArgs;
export const PlasmicTableRow__VariantProps = new Array<VariantPropType>(
  "header"
);

export type PlasmicTableRow__ArgsType = {
  topic?: React.ReactNode;
  price?: React.ReactNode;
  amount?: React.ReactNode;
  total?: React.ReactNode;
};

type ArgPropType = keyof PlasmicTableRow__ArgsType;
export const PlasmicTableRow__ArgProps = new Array<ArgPropType>(
  "topic",
  "price",
  "amount",
  "total"
);

export type PlasmicTableRow__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultTableRowProps {
  topic?: React.ReactNode;
  price?: React.ReactNode;
  amount?: React.ReactNode;
  total?: React.ReactNode;
  header?: SingleBooleanChoiceArg<"header">;
  className?: string;
}

function PlasmicTableRow__RenderFunc(props: {
  variants: PlasmicTableRow__VariantsArgs;
  args: PlasmicTableRow__ArgsType;
  overrides: PlasmicTableRow__OverridesType;
  dataFetches?: PlasmicTableRow__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.freeBox__ijd0C)}>
        {p.renderPlasmicSlot({
          defaultContents: "システム開発",
          value: args.topic
        })}
      </div>

      <div className={classNames(defaultcss.all, sty.freeBox__iCVvl)}>
        {p.renderPlasmicSlot({
          defaultContents: "4000",
          value: args.price
        })}
      </div>

      <div className={classNames(defaultcss.all, sty.freeBox__ivVOo)}>
        {p.renderPlasmicSlot({
          defaultContents: "30時間",
          value: args.amount
        })}
      </div>

      <div className={classNames(defaultcss.all, sty.freeBox__cQkAc)}>
        {p.renderPlasmicSlot({
          defaultContents: "120000",
          value: args.total
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTableRow__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTableRow__VariantsArgs;
    args?: PlasmicTableRow__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTableRow__Fetches;
  } & Omit<PlasmicTableRow__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTableRow__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTableRow__ArgProps,
      internalVariantPropNames: PlasmicTableRow__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTableRow__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTableRow";
  } else {
    func.displayName = `PlasmicTableRow.${nodeName}`;
  }
  return func;
}

export const PlasmicTableRow = Object.assign(
  // Top-level PlasmicTableRow renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTableRow
    internalVariantProps: PlasmicTableRow__VariantProps,
    internalArgProps: PlasmicTableRow__ArgProps
  }
);

export default PlasmicTableRow;
/* prettier-ignore-end */
