// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: j56rC5AhmHAm1fzGMT7yJp
// Component: k6tMcidfEC
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_react_invoice.module.css"; // plasmic-import: j56rC5AhmHAm1fzGMT7yJp/projectcss
import * as sty from "./PlasmicRecipient.module.css"; // plasmic-import: k6tMcidfEC/css

export type PlasmicRecipient__VariantMembers = {
  individual: "individual";
};

export type PlasmicRecipient__VariantsArgs = {
  individual?: SingleBooleanChoiceArg<"individual">;
};

type VariantPropType = keyof PlasmicRecipient__VariantsArgs;
export const PlasmicRecipient__VariantProps = new Array<VariantPropType>(
  "individual"
);

export type PlasmicRecipient__ArgsType = {
  name?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRecipient__ArgsType;
export const PlasmicRecipient__ArgProps = new Array<ArgPropType>("name");

export type PlasmicRecipient__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultRecipientProps {
  name?: React.ReactNode;
  individual?: SingleBooleanChoiceArg<"individual">;
  className?: string;
}

function PlasmicRecipient__RenderFunc(props: {
  variants: PlasmicRecipient__VariantsArgs;
  args: PlasmicRecipient__ArgsType;
  overrides: PlasmicRecipient__OverridesType;
  dataFetches?: PlasmicRecipient__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: "超誠覇神Z",
        value: args.name
      })}

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.freeBox,
          {
            [sty.freeBox__individual]: hasVariant(
              variants,
              "individual",
              "individual"
            )
          }
        )}
      >
        {hasVariant(variants, "individual", "individual") ? "様" : "御中"}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRecipient__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRecipient__VariantsArgs;
    args?: PlasmicRecipient__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRecipient__Fetches;
  } & Omit<PlasmicRecipient__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRecipient__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRecipient__ArgProps,
      internalVariantPropNames: PlasmicRecipient__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRecipient__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRecipient";
  } else {
    func.displayName = `PlasmicRecipient.${nodeName}`;
  }
  return func;
}

export const PlasmicRecipient = Object.assign(
  // Top-level PlasmicRecipient renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicRecipient
    internalVariantProps: PlasmicRecipient__VariantProps,
    internalArgProps: PlasmicRecipient__ArgProps
  }
);

export default PlasmicRecipient;
/* prettier-ignore-end */
